### ISSUE TITLE
Load records from EDG

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#27]
_From @torrin47 on August 31, 2018 23:4_

Once authenticated, internal (or ORCID authenticated?) users will be able to either create new records or select from existing records in the EDG to load into the editor. This will be limited to records previously posted using this editor – users will need to contact the EDG team to edit records that were harvested to the EDG via another channel.

_Copied from original issue: USEPA/EPA_Environmental_Dataset_Gateway#62_

**Comment by torrin47** [comment]
Output from EDG is not faithful to source DCAT, which means we can't read the full record from the EDG and as an alternative, we should have a way to read from the source DCAT JSON.  Closing this ticket and opening new tickets for... 

- Creating directory listing (json pointers?) of all EDG source dcat json files.
- Allow PODME to read directory listing and allow user to select source metadata record for updating.

**Comment by torrin47** [comment]
Not going to create new ticket for the second bullet above - instead will continue tracking here per the plan described.  Directory listing tracked in #99 .

**Comment by aergul** [comment]
This is in progress and not fully functional or polished yet. However, I pushed it to dev in case there is desire to provide early feedback.

It should show the repos and the records within:

![image.png](https://images.zenhubusercontent.com/5b888c67b1ed9a7d4f8504bf/fcfa3802-743a-49ba-b22c-acb3594ac42a)

![image.png](https://images.zenhubusercontent.com/5b888c67b1ed9a7d4f8504bf/77fc84ee-536a-48c5-a40d-b545623d65cd)

**Comment by torrin47** [comment]
Dang this is nice. Love it.

**Comment by torrin47** [comment]
Slick, I've tested and haven't been able to find any bugs or issues.

**Comment by jzichichi** [comment]
@aergul - this looks great to me.  I also did not find any issues here yet.  Love it.

**Comment by torrin47** [comment]
Ok, spent a bit more time reviewing this afternoon. 

First, I was surprised that without logging in, a user is still shown the universe of EPA records to potentially load into the editor. I'm pondering whether to treat this as a bug or a feature - extramurals wouldn't ever be editing internal records, but since all of the records are public, maybe it does no harm to show extramural folks our "model" records as an example? What are your thoughts? Would it be difficult to limit the load functionality to local files if a user isn't logged in? @charness39 didn't include the extramural repo in the list, but we could do so and allow extramurals to select their previously submitted records? Seems like it could be a "feature".

I was having some odd issues with the distribution sections not loading URLs from the metadata, but after a refresh the problem disappeared, so maybe it was a phantom effect. There is a different problem, though, that does consistently affect the Distribution section after loading a record - if one chooses to edit any field in a distribution section it will allow one character (or a paste) and then stop editing.  Kind of annoying if you'd like to add a title for a distribution. Are you seeing this on your end?

**Comment by aergul** [comment]
It wouldn't be difficult to make display of repos conditional on user's login status. For flexibility, it could be driven by an additional attribute in the master list of repos. Say:
```
{
  "title": ...
  "file": ...
  "epaOnly": false
}
```
which defaults to `true` if not specified. So you could specify it for extramural repo only when added and we could let extramural researchers pick from there whereas EPA users pick from AAship repos.

Or some variant of this scheme...

**Comment by torrin47** [comment]
That seems reasonable - let's discuss more on Wednesday and see whether Mike has an opinion either way.

Will do.

**Comment by torrin47** [comment]
We'll update the json listing with the proposed attribute, let's go with Ayhan's plan.

**Comment by aergul** [comment]
Plan implemented.
Also, user can now load another record from the same repo again without switching repos back and forth.

**Comment by jzichichi** [comment]
@aergul - the load feature shows when I first visit the page, but then it looks like the application hangs a little if I either sign in, then sign out, or if I click somewhere else after I have clicked the load feature once, the load option goes away and the app looks like it's hanging somewhat - because the EPA flower keeps spinning.  See image.  
![load_file](https://user-images.githubusercontent.com/13878970/65193171-2da80f80-da48-11e9-8055-4e0a3a0f92b7.png)

**Comment by aergul** [comment]
@jzichichi apologies, in my haste I hadn't deployed. I did now.

**Comment by jzichichi** [comment]
@aergul - the feature works better in that I now do not see repos when I am not logged in, however, it still has the issue that if I click load, then click elsewhere on the screen to not actually load anything, the load feature disappears from the list of available options when I go back to try again - as shown in image above.  Not sure why it disappears.

**Comment by jzichichi** [comment]
@torrin47 - realized the issue I am noticing is exactly the same as what you noted yesterday.  The items covered in this ticket seem to be working for me - the load repos shows no offices when not logged in, but allows me to select a local file, and then when logged in it does show the repos.  I will pass it along your way for additional testing and I suppose we can create a separate ticket for the weird missing load function (that shows back up if you scroll) if needed?

**Comment by torrin47** [comment]
Thanks @aergul and @jzichichi, the improvements are great, @charness39 is working on a placeholder extramural record for non-logged in users until we get our first real extramural record.  I'll create a separate ticket for the load button disappearing, it's pretty minor in the scheme of things.
